In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [2]:
train = pd.read_csv("/kaggle/input/competitions/data-science-london-scikit-learn/train.csv",header=None)
test = pd.read_csv("/kaggle/input/competitions/data-science-london-scikit-learn/test.csv",header=None)
labels = pd.read_csv("/kaggle/input/competitions/data-science-london-scikit-learn/trainLabels.csv",header=None)

In [3]:
train.head()

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,0.299403,-1.226624,1.498425,-1.176150,5.289853,0.208297,2.404498,1.594506,-0.051608,0.663234,...,-0.850465,-0.622990,-1.833057,0.293024,3.552681,0.717611,3.305972,-2.715559,-2.682409,0.101050
1,-1.174176,0.332157,0.949919,-1.285328,2.199061,-0.151268,-0.427039,2.619246,-0.765884,-0.093780,...,-0.819750,0.012037,2.038836,0.468579,-0.517657,0.422326,0.803699,1.213219,1.382932,-1.817761
2,1.192222,-0.414371,0.067054,-2.233568,3.658881,0.089007,0.203439,-4.219054,-1.184919,-1.240310,...,-0.604501,0.750054,-3.360521,0.856988,-2.751451,-1.582735,1.672246,0.656438,-0.932473,2.987436
3,1.573270,-0.580318,-0.866332,-0.603812,3.125716,0.870321,-0.161992,4.499666,1.038741,-1.092716,...,1.022959,1.275598,-3.480110,-1.065252,2.153133,1.563539,2.767117,0.215748,0.619645,1.883397
4,-0.613071,-0.644204,1.112558,-0.032397,3.490142,-0.011935,1.443521,-4.290282,-1.761308,0.807652,...,0.513906,-1.803473,0.518579,-0.205029,-4.744566,-1.520015,1.830651,0.870772,-1.894609,0.408332

In [4]:
test.head()

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,2.808909,-0.242894,-0.546421,0.255162,1.749736,-0.030458,-1.322071,3.578071,-0.667578,-0.884257,...,-0.261688,-0.224375,-1.675606,-0.479584,-0.244388,-0.672355,0.517860,0.010665,-0.419214,2.818387
1,-0.374101,0.537669,0.081063,0.756773,0.915231,2.557282,3.703187,1.673835,-0.764122,-1.228040,...,-0.969463,0.574154,-2.200519,-1.612240,0.179031,-2.924596,0.643610,-1.470939,-0.067408,-0.976265
2,-0.088370,0.154743,0.380716,-1.176126,1.699867,-0.258627,-1.384999,1.093584,1.596633,0.230631,...,-0.769885,-0.005143,1.467490,0.483803,-3.542981,0.814561,-1.652948,1.265866,-1.749248,1.773784
3,-0.685635,0.501283,1.873375,0.215224,-3.983468,-0.103637,4.136113,-0.225431,-1.515015,-1.071763,...,0.968609,2.386412,-0.131219,0.285646,2.302069,1.255588,-1.563090,-0.125258,-1.030761,-2.945329
4,0.350867,0.721897,-0.477104,-1.748776,-2.627405,1.075433,4.954253,-3.293501,-0.760369,0.204360,...,0.260553,-2.045650,-2.173227,0.372992,0.450700,-0.211657,1.301359,-0.522164,2.484883,0.039213

In [5]:
labels.head()
labels.columns = ['target']

In [6]:
df = train.join(labels,how='inner')
df

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,target
0,0.299403,-1.226624,1.498425,-1.176150,5.289853,0.208297,2.404498,1.594506,-0.051608,0.663234,...,-0.622990,-1.833057,0.293024,3.552681,0.717611,3.305972,-2.715559,-2.682409,0.101050,1
1,-1.174176,0.332157,0.949919,-1.285328,2.199061,-0.151268,-0.427039,2.619246,-0.765884,-0.093780,...,0.012037,2.038836,0.468579,-0.517657,0.422326,0.803699,1.213219,1.382932,-1.817761,0
2,1.192222,-0.414371,0.067054,-2.233568,3.658881,0.089007,0.203439,-4.219054,-1.184919,-1.240310,...,0.750054,-3.360521,0.856988,-2.751451,-1.582735,1.672246,0.656438,-0.932473,2.987436,0
3,1.573270,-0.580318,-0.866332,-0.603812,3.125716,0.870321,-0.161992,4.499666,1.038741,-1.092716,...,1.275598,-3.480110,-1.065252,2.153133,1.563539,2.767117,0.215748,0.619645,1.883397,1
4,-0.613071,-0.644204,1.112558,-0.032397,3.490142,-0.011935,1.443521,-4.290282,-1.761308,0.807652,...,-1.803473,0.518579,-0.205029,-4.744566,-1.520015,1.830651,0.870772,-1.894609,0.408332,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,-0.310429,0.826811,-0.952245,0.768850,1.877520,1.320646,1.944609,1.191420,-0.127724,0.070937,...,-0.383792,0.745596,-0.698598,-2.729937,-0.431535,0.372873,1.019092,-2.672811,-0.295141,0
996,-1.853879,0.246726,0.459921,-2.074267,7.599220,-0.138355,-4.501900,0.630634,-1.590533,-1.112949,...,0.240052,-0.856196,-0.072481,-2.935896,0.582411,-2.613407,0.036687,2.809310,4.412567,1
997,0.912748,-1.734039,-1.047035,0.217573,13.457812,0.162771,-2.250521,2.216161,-0.378326,0.642114,...,-1.073806,-2.754369,1.814864,-4.190105,-1.116441,-2.100125,0.061513,0.895536,0.813686,1
998,2.439780,-0.735511,-0.902426,1.365036,-10.430299,-0.856859,2.686474,0.292035,0.585388,-0.876965,...,-0.039488,0.773876,-0.916066,2.604827,-0.649874,-3.423674,0.229748,-2.311088,-3.422217,0
999,0.228994,-0.085453,0.876582,1.057401,-1.404015,-1.091965,0.639176,0.701332,-0.906577,-0.390940,...,1.024757,-1.796571,0.603161,0.862705,0.747234,3.275681,0.400372,-3.431031,2.370080,0

In [7]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,target
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,0.025596,-0.024526,-0.024088,-0.002271,1.092329,-0.006250,0.497342,-0.037883,0.026391,-0.003597,...,0.022951,-0.542491,-0.011608,-0.483507,0.033371,0.567185,0.006849,-0.892659,0.609451,0.51000
std,1.008282,1.016298,0.979109,0.970575,4.538834,0.989128,2.118819,2.232256,1.001064,1.013520,...,1.001375,2.239939,1.022456,2.121281,1.007044,2.227876,0.997635,2.022022,2.045439,0.50015
min,-3.365711,-3.492086,-2.695602,-3.460471,-16.421901,-3.041250,-7.224761,-6.509084,-3.145588,-2.749812,...,-2.971125,-7.840890,-2.999564,-7.124105,-2.952358,-5.452254,-3.473913,-8.051722,-7.799086,0.00000
25%,-0.669010,-0.693937,-0.698830,-0.617557,-1.801997,-0.732265,-0.838619,-1.604037,-0.677562,-0.682220,...,-0.696032,-2.121943,-0.664550,-1.879247,-0.642861,-1.059786,-0.691162,-2.220126,-0.565041,0.00000
50%,0.027895,-0.033194,0.008145,0.002327,0.862818,0.027041,0.582321,0.018809,0.022092,-0.036110,...,0.049778,-0.568262,-0.028097,-0.493575,0.037732,0.455474,0.038284,-0.855470,0.779944,1.00000
75%,0.762520,0.682753,0.661434,0.640743,3.843172,0.671456,1.913664,1.438304,0.741310,0.665364,...,0.699917,0.939348,0.651374,1.005795,0.691800,2.122157,0.693535,0.388698,1.992193,1.00000
max,3.326246,3.583870,2.546507,3.088738,17.565345,3.102997,7.592666,7.130097,3.145258,3.919426,...,3.688047,7.160379,3.353631,6.005818,3.420561,6.603499,3.492548,5.774120,6.803984,1.00000

In [8]:
df.corr()

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,target
0,1.000000,-0.029022,0.033437,0.012054,-0.022404,0.037209,0.019134,0.015277,-0.045568,-0.023777,...,0.023033,-0.004701,0.005180,0.012961,0.047455,-0.026327,0.038844,0.016098,-0.045840,-0.028058
1,-0.029022,1.000000,0.014202,0.009663,0.044758,-0.034173,-0.008474,0.006568,0.039895,0.008368,...,-0.052864,0.005583,0.009125,-0.026617,0.053087,0.039265,0.019537,-0.046295,-0.005667,-0.052153
2,0.033437,0.014202,1.000000,0.007579,0.019658,-0.013532,-0.054348,-0.008825,0.019443,-0.015920,...,-0.002177,-0.038702,0.046611,0.008141,0.014150,0.020865,0.030127,-0.004390,0.020101,-0.005618
3,0.012054,0.009663,0.007579,1.000000,0.023827,0.021305,-0.028903,-0.044407,0.001253,-0.049892,...,-0.006878,-0.030960,-0.018130,-0.055653,0.024811,0.048042,0.016295,0.041164,0.021217,-0.007439
4,-0.022404,0.044758,0.019658,0.023827,1.000000,0.027705,-0.338883,0.206964,0.063638,0.079723,...,0.007981,-0.325592,0.031156,-0.212497,0.015455,0.016657,0.021133,-0.084677,-0.227957,0.150652
5,0.037209,-0.034173,-0.013532,0.021305,0.027705,1.000000,-0.068367,0.036041,0.031510,-0.023893,...,-0.050032,0.016181,0.017013,0.019377,-0.034101,-0.009464,-0.046527,0.032984,0.013334,0.015151
6,0.019134,-0.008474,-0.054348,-0.028903,-0.338883,-0.068367,1.000000,-0.000915,-0.031153,0.065493,...,-0.020219,-0.105353,-0.025403,0.171086,-0.003786,0.090158,0.075050,-0.141340,-0.233928,-0.252976
7,0.015277,0.006568,-0.008825,-0.044407,0.206964,0.036041,-0.000915,1.000000,0.026522,0.040061,...,0.000762,0.049853,-0.040604,0.115860,-0.014349,0.124554,0.017283,-0.049654,-0.150962,0.040523
8,-0.045568,0.039895,0.019443,0.001253,0.063638,0.031510,-0.031153,0.026522,1.000000,0.016758,...,0.011961,-0.076989,-0.012986,0.016908,0.005058,-0.007465,0.015940,-0.019059,-0.041355,0.037534
9,-0.023777,0.008368,-0.015920,-0.049892,0.079723,-0.023893,0.065493,0.040061,0.016758,1.000000,...,0.055498,-0.037393,0.010608,-0.058954,0.001854,-0.004522,-0.034966,-0.020446,-0.070172,0.026841
10,-0.037427,0.022105,0.011994,-0.031417,-0.051509,-0.004594,-0.006394,-0.021951,-0.022337,0.046935,...,0.018423,0.038048,0.019366,0.011873,0.021806,-0.045234,-0.011955,-0.013516,0.026616,-0.010233
11,0.012477,-0.034953,0.023328,0.052135,-0.019005,-0.058050,0.036516,-0.003977,-0.033289,0.019443,...,-0.000034,0.020030,0.020090,-0.036264,-0.001962,0.038142,-0.019648,0.040810,-0.020987,-0.075276
12,-0.004410,-0.065364,0.026965,-0.048933,-0.184640,0.043318,-0.419642,0.056134,0.051579,-0.076660,...,0.034641,-0.095718,-0.052491,0.453173,-0.004232,-0.182658,-0.046350,0.090493,0.110447,0.460738
13,0.044999,-0.039695,-0.003345,-0.031286,0.050186,-0.003975,0.001454,0.012564,0.028123,0.014033,...,0.003951,-0.047729,0.002338,-0.002142,0.048044,0.000486,0.001191,0.017037,-0.057128,0.018214
14,0.002984,-0.069600,-0.024474,-0.044111,0.209115,0.016991,-0.184330,-0.021095,0.017060,0.004008,...,0.007467,-0.031780,-0.000320,0.148442,-0.009477,-0.114092,0.029476,-0.164538,0.092740,0.476171
15,0.006890,-0.001228,0.014957,-0.046394,0.011283,0.002038,-0.004506,-0.008298,0.016582,0.020943,...,0.012588,0.043055,-0.016423,-0.004044,-0.021116,0.001448,0.001919,-0.006399,-0.042175,-0.060556
16,0.023151,-0.033658,0.037882,0.038765,-0.010417,-0.004314,0.059714,-0.011443,0.036039,0.010802,...,-0.011451,-0.073987,0.065442,0.025378,-0.063987,-0.006681,-0.012295,0.041778,0.013661,0.012234
17,0.039499,0.044709,0.054775,0.015674,-0.001717,-0.000589,-0.043495,-0.056082,-0.004586,-0.087833,...,-0.016741,-0.028353,0.003116,0.013375,-0.014939,0.008701,0.028183,0.040681,0.026468,-0.018021
18,-0.051614,0.018864,0.001878,-0.017277,0.080150,0.039427,-0.107176,0.130023,0.008089,-0.010817,...,0.016622,-0.003343,0.006133,-0.033309,0.028044,-0.042455,0.006534,-0.282431,0.300155,0.289508
19,0.004408,0.009298,-0.005757,0.025663,0.025250,-0.042694,-0.004120,-0.044051,0.000207,0.010940,...,-0.067189,-0.021787,0.038550,-0.003289,-0.027955,0.001016,-0.032087,0.027369,0.009386,0.046036
20,-0.001347,0.021246,0.053421,-0.002158,0.004765,0.044357,0.024973,0.056280,0.059946,0.030396,...,-0.056389,0.020425,-0.018514,-0.026723,0.010036,0.078414,-0.026363,-0.028073,-0.036576,-0.075135
21,0.016485,0.020263,0.004037,-0.008345,0.009427,-0.041301,-0.030886,-0.002344,-0.062792,-0.000048,...,-0.027499,0.010885,0.044612,-0.017645,0.012711,-0.021266,0.037789,0.001307,-0.012076,-0.018645
22,0.021047,0.044744,-0.010850,-0.012444,0.449976,-0.024654,0.116646,0.069903,0.027927,0.059458,...,-0.008018,-0.075722,0.045062,-0.006324,-0.014390,-0.135267,0.045044,-0.279579,-0.109855,0.046953
23,-0.020664,0.051050,0.051547,0.013371,0.568959,0.003663,-0.217741,-0.113899,0.090151,0.015708,...,0.032428,-0.453138,0.008407,0.257133,0.012386,0.204730,0.003117,-0.306711,-0.310490,0.172938
24,-0.028256,0.020862,0.001834,-0.034712,-0.059516,-0.003748,0.070511,-0.058485,0.001375,-0.013757,...,0.011665,-0.014389,-0.002748,-0.012643,0.008924,-0.024168,-0.023394,0.007385,-0.000780,-0.017121
25,-0.014671,0.019272,-0.006478,-0.017270,0.024766,-0.022389,0.054907,0.007029,0.004733,0.020467,...,-0.027106,-0.040435,-0.019240,0.029309,-0.015760,0.039201,-0.027665,0.039480,-0.031934,-0.036663
26,0.047728,0.010341,-0.017693,0.040604,-0.016014,0.029581,-0.013347,0.013849,-0.020321,0.057604,...,-0.000785,0.013379,-0.011437,-0.010916,-0.036908,-0.013289,0.021426,0.010005,0.045605,0.064633
27,-0.060396,-0.002228,-0.009868,0.021951,0.049695,-0.006412,-0.014378,-0.036551,-0.013502,0.002832,...,-0.031253,-0.055318,-0.051371,0.030509,0.009340,-0.040914,-0.003187,0.018008,0.052344,0.019778
28,0.026154,-0.067760,0.005040,-0.033828,-0.522373,-0.021571,0.048105,0.045134,0.032840,-0.045896,...,0.018346,-0.086240,-0.059175,0.293913,-0.025472,0.018826,-0.013701,0.180924,0.283127,0.207949
29,0.031174,-0.010763,-0.005418,0.032422,-0.465130,0.010774,0.069492,-0.025301,-0.031475,-0.034611,...,0.019592,-0.110933,0.008248,0.137749,-0.023510,0.241248,0.010129,0.049550,0.287253,-0.012022
30,0.012446,-0.000782,0.034527,0.025678,-0.039205,0.011408,-0.050016,-0.037795,0.016460,-0.039496,...,-0.024786,0.005798,-0.026837,-0.016300,-0.038520,-0.073321,-0.061697,0.028444,0.018338,-0.015797
31,0.023033,-0.052864,-0.002177,-0.006878,0.007981,-0.050032,-0.020219,0.000762,0.011961,0.055498,...,1.000000,-0.027278,-0.003418,0.006635,-0.031574,-0.005343,0.003566,-0.004915,-0.016312,0.012458
32,-0.004701,0.005583,-0.038702,-0.030960,-0.325592,0.016181,-0.105353,0.049853,-0.076989,-0.037393,...,-0.027278,1.000000,0.015406,-0.259151,-0.009889,-0.050540,-0.038393,-0.197690,-0.110049,-0.227027
33,0.005180,0.009125,0.046611,-0.018130,0.031156,0.017013,-0.025403,-0.040604,-0.012986,0.010608,...,-0.003418,0.015406,1.000000,-0.049568,-0.047772,-0.019554,0.009121,-0.030572,0.024840,-0.053928
34,0.012961,-0.026617,0.008141,-0.055653,-0.212497,0.019377,0.171086,0.115860,0.016908,-0.058954,...,0.006635,-0.259151,-0.049568,1.000000,-0.035899,0.107606,-0.022208,0.145990,-0.147988,0.236116
35,0.047455,0.053087,0.014150,0.024811,0.015455,-0.034101,-0.003786,-0.014349,0.005058,0.001854,...,-0.031574,-0.009889,-0.047772,-0.035899,1.000000,-0.016145,-0.007901,-0.038879,0.014993,0.012533
36,-0.026327,0.039265,0.020865,0.048042,0.016657,-0.009464,0.090158,0.124554,-0.007465,-0.004522,...,-0.005343,-0.050540,-0.019554,0.107606,-0.016145,1.000000,-0.009176,0.000086,-0.046425,-0.231733
37,0.038844,0.019537,0.030127,0.016295,0.021133,-0.046527,0.075050,0.017283,0.015940,-0.034966,...,0.003566,-0.038393,0.009121,-0.022208,-0.007901,-0.009176,1.000000,-0.059341,-0.021385,0.039376
38,0.016098,-0.046295,-0.004390,0.041164,-0.084677,0.032984,-0.141340,-0.049654,-0.019059,-0.020446,...,-0.004915,-0.197690,-0.030572,0.145990,-0.038879,0.000086,-0.059341,1.000000,0.223299,-0.019690
39,-0.045840,-0.005667,0.020101,0.021217,-0.227957,0.013334,-0.233928,-0.150962,-0.041355,-0.070172,...,-0.016312,-0.110049,0.024840,-0.147988,0.014993,-0.046425,-0.021385,0.223299,1.000000,0.264656
target,-0.028058,-0.052153,-0.005618,-0.007439,0.150652,0.015151,-0.252976,0.040523,0.037534,0.026841,...,0.012458,-0.227027,-0.053928,0.236116,0.012533,-0.231733,0.039376,-0.019690,0.264656,1.000000

In [9]:
pipeline = make_pipeline(
    StandardScaler(),
    KNeighborsClassifier(n_neighbors=5, weights = "uniform", p=2, metric='minkowski')
)

In [10]:
pipeline.fit(train,labels)

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('kneighborsclassifier', KNeighborsClassifier())])

In [11]:
preds = pipeline.predict(test)

In [12]:
submission = pd.DataFrame({
    "Solution":preds
})

submission.index = submission.index + 1

submission =  submission.reset_index().rename(columns={"index": "Id"})

submission

        Id  Solution
0        1         1
1        2         0
2        3         1
3        4         0
4        5         0
...    ...       ...
8995  8996         1
8996  8997         1
8997  8998         1
8998  8999         0
8999  9000         1

[9000 rows x 2 columns]

In [13]:
submission.to_csv("submission.csv",index=False)